create table if not exists public.products (
  id bigint generated by default as identity primary key,
  sl_no integer,
  api_name text,
  impurity_name text not null,
  cat_no text,
  cas_no text,
  iupac text,
  mf text,
  mw text,
  storage text,
  inv_status text,
  synonyms text not null default '',
  synonyms_text text not null default '',
  structure text,
  created_at timestamptz not null default now()
);

alter table public.products
  drop column if exists impurity;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'products'
      and column_name = 'synonyms'
      and udt_name = '_text'
  ) then
    alter table public.products
      alter column synonyms drop default,
      alter column synonyms type text
      using case
        when synonyms is null then ''
        else array_to_string(synonyms, ', ')
      end,
      alter column synonyms set default '';
  end if;
end $$;

alter table public.products
  alter column synonyms set not null;

alter table public.products
  add column if not exists synonyms_text text not null default '';

update public.products
set synonyms_text = coalesce(synonyms, '')
where synonyms_text = '';

create or replace function public.sync_products_synonyms_text()
returns trigger
language plpgsql
as $$
begin
  new.synonyms_text := coalesce(new.synonyms, '');
  return new;
end;
$$;

drop trigger if exists products_sync_synonyms_text on public.products;

create trigger products_sync_synonyms_text
before insert or update of synonyms
on public.products
for each row
execute function public.sync_products_synonyms_text();

drop index if exists products_impurity_na_idx;
create index if not exists products_impurity_name_idx on public.products using btree (impurity_name);
create index if not exists products_api_name_idx on public.products using btree (api_name);
create index if not exists products_cas_no_idx on public.products using btree (cas_no);
create index if not exists products_cat_no_idx on public.products using btree (cat_no);

alter table public.products enable row level security;

drop policy if exists "Public can read products" on public.products;

create policy "Public can read products"
on public.products
for select
to public
using (true);
